version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=parking
    ports:
      - 5432:5432
  smart-park-identy-back:
    image: smart-parking-identy_smart-park-identy-back
    environment:
      IDENTY_DATABASE_URI: postgresql://root:root@postgres:5432/identy
      IDENTY_SECRET: super_secret
      IDENTY_REFRESH_SECRET: refresh_super_secret
    ports:
      - 8080:3000
  smart-park-back:
    build: .
    environment:
      PARKING_DATABASE_URI: postgresql://root:root@postgres:5432/parking
      PARKING_AUTH_API_URI: http://smart-park-identy-back:3000
    ports:
      - 5002:3001